# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Joshwrn.JiraBranch
PackageVersion: 0.1.0
PackageLocale: en-US
Publisher: Joshwrn
PublisherUrl: https://github.com/joshwrn
PublisherSupportUrl: https://github.com/joshwrn/jira-branch/issues
PackageName: Jira Branch
PackageUrl: https://github.com/joshwrn/jira-branch
License: MIT License
ShortDescription: A terminal app for quickly creating new git branches with Jira ticket summaries
ReleaseNotesUrl: https://github.com/joshwrn/jira-branch/releases/tag/v0.1.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
