# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Joshwrn.JiraBranch
PackageVersion: 0.1.0
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/joshwrn/jira-branch/releases/download/v0.1.0/jira-branch-v0.1.0-windows-x64.exe
  InstallerSha256: B6CB34073A1C08DAD224012C49EC1A33C17CEF3FAD6091D19CC9B6F63C397B8A
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2025-07-12
